name: abiz_pos
description: A Biz Pos

publish_to: "none"

version: 1.5.15+22

environment:
  #  sdk: ">=2.19.2 <3.0.0"

  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.2
  cached_network_image: ^3.2.1
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.1
  equatable: ^2.0.5
  flat_buffers: ^23.5.26
  qr: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  flutter_svg: ^2.0.4
  flutter_typeahead: ^5.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^1.2.0
  in_app_notification: ^1.1.1
  intl: ^0.18.0
  mask_text_input_formatter: ^2.3.0
  package_info_plus: ^5.0.1
  path_provider: ^2.0.0
  pdf: ^3.10.6
  pin_code_fields: ^8.0.1
  printing: ^5.12.0
  shell: ^2.0.0
  web_socket_channel: 2.4.0
  virtual_keyboard_flutter: ^1.0.0
  visibility_detector: ^0.4.0+2
  windows1251: ^2.0.0
#  fluttertoast: ^8.2.2
  json_annotation: ^4.8.1
#  shelf: ^1.4.1
  reorderable_grid_view: ^2.2.8
#  firedart: ^0.9.7
#  firebase_core: ^2.25.3
#  googleapis_auth: ^1.4.2
  dio: ^5.4.1



dev_dependencies:
  build_runner: ^2.4.6
  # integration_test:
  #   sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  msix: ^3.9.1

flutter_icons:
  image_path: ""

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/


  fonts:

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400






msix_config:
  display_name: Abiz POS
  publisher_display_name: Abiz POS
  identity_name: abiz.uz.company.inVanPosDesktop
  msix_version: 1.4.0.0
  logo_path: D:\icon.png
  start_menu_icon_path: D:\icon.png
  tile_icon_path: D:\icon.png
  dont_install_cert: true
